theme: jekyll-theme-cayman
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-205611901-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-205611901-1');
</script>
# Google Analytics
google_analytics: UA-205611901-1
